In [2]:
import yfinance as yf

In [3]:
stock=input("Enter stock symbol").upper()
STOCK=yf.Ticker(stock)

Enter stock symbolMSFT

In [8]:
STOCK_REC=STOCK.recommendations

In [9]:
STOCK_HIS=STOCK.history(period='1mo',interval='1d')

In [12]:
STOCK_HIS.drop(columns=['Dividends','Stock Splits'],inplace=True)
STOCK_HIS

              Open    High     Low   Close    Volume
Date
2020-11-25  215.11  215.29  212.46  213.87  21012900
2020-11-27  214.85  216.27  214.04  215.23  14512200
2020-11-30  214.10  214.76  210.84  214.07  33064800
2020-12-01  214.51  217.32  213.35  216.21  30931300
2020-12-02  214.88  215.47  212.80  215.37  23724500
2020-12-03  214.61  216.38  213.65  214.24  25120900
2020-12-04  214.22  215.38  213.18  214.36  24666000
2020-12-07  214.37  215.54  212.99  214.29  24620000
2020-12-08  213.97  216.95  212.89  216.01  23284100
2020-12-09  215.16  215.23  211.21  211.80  32440600
2020-12-10  211.77  213.08  210.36  210.52  26733300
2020-12-11  210.05  213.32  209.11  213.26  30979400
2020-12-14  213.10  216.21  212.88  214.20  28798400
2020-12-15  215.17  215.42  212.24  214.13  27018100
2020-12-16  214.75  220.11  214.72  219.28  35023300
2020-12-17  219.87  220.89  217.92  219.42  32515800
2020-12-18  218.59  219.69  216.02  218.59  63354900
2020-12-21  217.55  224.00  217.28  222.59  37181900
2020-12-22  222.69  225.63  221.85  223.94  22612200
2020-12-23  223.11  223.56  220.80  221.02  18699600
2020-12-24  221.42  223.61  221.20  222.75  10550600

In [66]:
STOCK_HIS['dow']=STOCK_HIS.index.dayofweek+1  # adjust the 0 to 1, and so forth

In [67]:
STOCK_HIS

              Open    High     Low   Close    Volume  dow
Date
2020-11-25  215.11  215.29  212.46  213.87  21012900    3
2020-11-27  214.85  216.27  214.04  215.23  14512200    5
2020-11-30  214.10  214.76  210.84  214.07  33064800    1
2020-12-01  214.51  217.32  213.35  216.21  30931300    2
2020-12-02  214.88  215.47  212.80  215.37  23724500    3
2020-12-03  214.61  216.38  213.65  214.24  25120900    4
2020-12-04  214.22  215.38  213.18  214.36  24666000    5
2020-12-07  214.37  215.54  212.99  214.29  24620000    1
2020-12-08  213.97  216.95  212.89  216.01  23284100    2
2020-12-09  215.16  215.23  211.21  211.80  32440600    3
2020-12-10  211.77  213.08  210.36  210.52  26733300    4
2020-12-11  210.05  213.32  209.11  213.26  30979400    5
2020-12-14  213.10  216.21  212.88  214.20  28798400    1
2020-12-15  215.17  215.42  212.24  214.13  27018100    2
2020-12-16  214.75  220.11  214.72  219.28  35023300    3
2020-12-17  219.87  220.89  217.92  219.42  32515800    4
2020-12-18  218.59  219.69  216.02  218.59  63354900    5
2020-12-21  217.55  224.00  217.28  222.59  37181900    1
2020-12-22  222.69  225.63  221.85  223.94  22612200    2
2020-12-23  223.11  223.56  220.80  221.02  18699600    3
2020-12-24  221.42  223.61  221.20  222.75  10550600    4

In [16]:
STOCK_REC=STOCK_REC.iloc[-15:,0:2]

In [26]:
STOCK_REC['To Grade'].value_counts()

Overweight    6
Buy           4
Outperform    3
Strong Buy    1
Perform       1
Name: To Grade, dtype: int64

In [25]:
#common data structure for Grade column
STOCK_REC['To Grade'].replace({'Overweight':'Buy','Strong Buy':'Buy',
                               'Outperform':'Buy',
                              'Perform':'Hold'})

Date
2020-07-20 14:48:02     Buy
2020-07-23 08:43:04     Buy
2020-07-23 13:06:12    Hold
2020-09-09 12:01:51     Buy
2020-10-13 16:40:00     Buy
2020-10-14 10:49:23     Buy
2020-10-20 16:25:09     Buy
2020-10-23 16:26:29     Buy
2020-10-28 09:02:04     Buy
2020-10-28 12:00:17     Buy
2020-10-28 13:22:56     Buy
2020-10-29 16:00:20     Buy
2020-11-05 10:48:37     Buy
2020-11-24 11:17:51     Buy
2020-12-21 12:04:59     Buy
Name: To Grade, dtype: object

In [27]:
STOCK_REC['To Grade']=STOCK_REC['To Grade'].replace({'Overweight':'Buy','Strong Buy':'Buy',
                               'Outperform':'Buy',
                              'Perform':'Hold'})

In [32]:
# replace values and common the values
STOCK_REC['Rating']=STOCK_REC['To Grade']  # 3s are Buys, 2s are holds, and 1s are sells

In [34]:
STOCK_REC['Rating'].replace(
    {'Buy':3,
    'Hold':2,
    'Sell':1
    }
)

Date
2020-07-20 14:48:02    3
2020-07-23 08:43:04    3
2020-07-23 13:06:12    2
2020-09-09 12:01:51    3
2020-10-13 16:40:00    3
2020-10-14 10:49:23    3
2020-10-20 16:25:09    3
2020-10-23 16:26:29    3
2020-10-28 09:02:04    3
2020-10-28 12:00:17    3
2020-10-28 13:22:56    3
2020-10-29 16:00:20    3
2020-11-05 10:48:37    3
2020-11-24 11:17:51    3
2020-12-21 12:04:59    3
Name: Rating, dtype: int64

In [35]:
STOCK_REC['Rating']=STOCK_REC['Rating'].replace(
    {'Buy':3,
    'Hold':2,
    'Sell':1
    }
)

In [37]:
STOCK_REC.rename(columns={'To Grade':'Grade'},inplace=True)
STOCK_REC

                               Firm Grade  Rating
Date
2020-07-20 14:48:02   Raymond James   Buy       3
2020-07-23 08:43:04   Piper Sandler   Buy       3
2020-07-23 13:06:12     Oppenheimer  Hold       2
2020-09-09 12:01:51  Morgan Stanley   Buy       3
2020-10-13 16:40:00     RBC Capital   Buy       3
2020-10-14 10:49:23             UBS   Buy       3
2020-10-20 16:25:09          Stifel   Buy       3
2020-10-23 16:26:29        Barclays   Buy       3
2020-10-28 09:02:04   Piper Sandler   Buy       3
2020-10-28 12:00:17  Morgan Stanley   Buy       3
2020-10-28 13:22:56   Credit Suisse   Buy       3
2020-10-29 16:00:20   Deutsche Bank   Buy       3
2020-11-05 10:48:37     Oppenheimer   Buy       3
2020-11-24 11:17:51         KeyBanc   Buy       3
2020-12-21 12:04:59       Citigroup   Buy       3

In [40]:
import json

In [54]:
def write_json(name:str,content:dict):
    with open(name, "w") as file_handle:
        json.dump(content,file_handle)

In [44]:
STOCK_REC['Firm'].values

array(['Raymond James', 'Piper Sandler', 'Oppenheimer', 'Morgan Stanley',
       'RBC Capital', 'UBS', 'Stifel', 'Barclays', 'Piper Sandler',
       'Morgan Stanley', 'Credit Suisse', 'Deutsche Bank', 'Oppenheimer',
       'KeyBanc', 'Citigroup'], dtype=object)

In [58]:
json_file={'firm':list(STOCK_REC['Firm'].values),
          'grade':list(STOCK_REC['Grade'].values)}
#           'rating':list(STOCK_REC['Rating'].values)}

In [59]:
write_json('stock.json',json_file)

In [ ]:
data=[
    {}
]

In [78]:
STOCK_HIS['dow']=STOCK_HIS['dow'].astype('str')

In [79]:
json_hist={
    'dates':list(STOCK_HIS.index.strftime('%Y-%m-%d').values),
    'open':list(STOCK_HIS.Open.values),
    'high':list(STOCK_HIS.High.values),
    'low':list(STOCK_HIS.Low.values),
    'close':list(STOCK_HIS.Close.values),
#     'volume':list(STOCK_HIS.Volume.values),
    'dow':list(STOCK_HIS.dow.values)
}
json_hist

{'dates': ['2020-11-25',
  '2020-11-27',
  '2020-11-30',
  '2020-12-01',
  '2020-12-02',
  '2020-12-03',
  '2020-12-04',
  '2020-12-07',
  '2020-12-08',
  '2020-12-09',
  '2020-12-10',
  '2020-12-11',
  '2020-12-14',
  '2020-12-15',
  '2020-12-16',
  '2020-12-17',
  '2020-12-18',
  '2020-12-21',
  '2020-12-22',
  '2020-12-23',
  '2020-12-24'],
 'open': [215.11,
  214.85,
  214.1,
  214.51,
  214.88,
  214.61,
  214.22,
  214.37,
  213.97,
  215.16,
  211.77,
  210.05,
  213.1,
  215.17,
  214.75,
  219.87,
  218.59,
  217.55,
  222.69,
  223.11,
  221.42],
 'high': [215.29,
  216.27,
  214.76,
  217.32,
  215.47,
  216.38,
  215.38,
  215.54,
  216.95,
  215.23,
  213.08,
  213.32,
  216.21,
  215.42,
  220.11,
  220.89,
  219.69,
  224.0,
  225.63,
  223.56,
  223.61],
 'low': [212.46,
  214.04,
  210.84,
  213.35,
  212.8,
  213.65,
  213.18,
  212.99,
  212.89,
  211.21,
  210.36,
  209.11,
  212.88,
  212.24,
  214.72,
  217.92,
  216.02,
  217.28,
  221.85,
  220.8,
  221.2],
 'close': [213.87,
  215.23,
  214.07,
  216.21,
  215.37,
  214.24,
  214.36,
  214.29,
  216.01,
  211.8,
  210.52,
  213.26,
  214.2,
  214.13,
  219.28,
  219.42,
  218.59,
  222.59,
  223.94,
  221.02,
  222.75],
 'dow': ['3',
  '5',
  '1',
  '2',
  '3',
  '4',
  '5',
  '1',
  '2',
  '3',
  '4',
  '5',
  '1',
  '2',
  '3',
  '4',
  '5',
  '1',
  '2',
  '3',
  '4']}

In [80]:
write_json('stock_h.json',json_hist)